'use client';

import { useEffect, useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

export default function AdminPage() {
  const [session, setSession] = useState<any>(null);
  const [email, setEmail] = useState(''); const [password, setPassword] = useState('');
  const [message, setMessage] = useState(''); const [proposalFile, setProposalFile] = useState<File | null>(null); const [mediaFile, setMediaFile] = useState<File | null>(null);
  const [proposalTitle, setProposalTitle] = useState(''); const [proposalDescription, setProposalDescription] = useState('');
  const [mediaTitle, setMediaTitle] = useState(''); const [mediaDescription, setMediaDescription] = useState('');

  useEffect(() => { supabase.auth.getSession().then(({ data }) => setSession(data.session)); const { data: listener } = supabase.auth.onAuthStateChange((_e, s) => setSession(s)); return () => listener.subscription.unsubscribe(); }, []);
  async function login(e: React.FormEvent) { e.preventDefault(); setMessage(''); const { error } = await supabase.auth.signInWithPassword({ email, password }); if (error) setMessage(error.message); }
  async function uploadProposal(e: React.FormEvent) { e.preventDefault(); if (!proposalFile || !proposalTitle) return setMessage('Add a proposal title and file.'); const path = `${Date.now()}-${proposalFile.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const up = await supabase.storage.from('project-proposals').upload(path, proposalFile); if (up.error) return setMessage(up.error.message); const { data } = supabase.storage.from('project-proposals').getPublicUrl(path); const ins = await supabase.from('project_proposals').insert({ title: proposalTitle, description: proposalDescription, file_url: data.publicUrl, file_name: proposalFile.name }); if (ins.error) return setMessage(ins.error.message); setMessage('Proposal published successfully.'); setProposalTitle(''); setProposalDescription(''); setProposalFile(null); }
  async function uploadMedia(e: React.FormEvent) { e.preventDefault(); if (!mediaFile) return setMessage('Choose an image or video.'); const type = mediaFile.type.startsWith('video/') ? 'video' : 'image'; const bucket = 'project-gallery'; const path = `${Date.now()}-${mediaFile.name.replace(/[^a-zA-Z0-9._-]/g, '-')}`; const up = await supabase.storage.from(bucket).upload(path, mediaFile); if (up.error) return setMessage(up.error.message); const { data } = supabase.storage.from(bucket).getPublicUrl(path); const ins = await supabase.from('gallery_items').insert({ title: mediaTitle, description: mediaDescription, media_type: type, media_url: data.publicUrl }); if (ins.error) return setMessage(ins.error.message); setMessage('Gallery item published successfully.'); setMediaTitle(''); setMediaDescription(''); setMediaFile(null); }
  if (!session) return <main className="admin-page"><div className="admin-card"><span className="eyebrow">ADMINISTRATION</span><h1>Content dashboard</h1><p>Sign in to publish project proposals, photographs and videos.</p><form onSubmit={login} className="admin-form"><input type="email" placeholder="Admin email" value={email} onChange={e => setEmail(e.target.value)} required /><input type="password" placeholder="Password" value={password} onChange={e => setPassword(e.target.value)} required /><button className="button" type="submit">Sign in</button></form>{message && <p className="notice">{message}</p>}</div></main>;
  return <main className="admin-page"><div className="admin-head"><div><span className="eyebrow">ADMINISTRATION</span><h1>Content dashboard</h1></div><button className="button secondary-dark" onClick={() => supabase.auth.signOut()}>Sign out</button></div><p className="notice">{message}</p><div className="admin-grid"><form className="admin-card admin-form" onSubmit={uploadProposal}><h2>Publish proposal</h2><input placeholder="Project title" value={proposalTitle} onChange={e => setProposalTitle(e.target.value)} required /><textarea placeholder="Short description" value={proposalDescription} onChange={e => setProposalDescription(e.target.value)} /><input type="file" accept="application/pdf,.doc,.docx" onChange={e => setProposalFile(e.target.files?.[0] || null)} required /><button className="button" type="submit">Upload & Publish</button></form><form className="admin-card admin-form" onSubmit={uploadMedia}><h2>Publish gallery media</h2><input placeholder="Title" value={mediaTitle} onChange={e => setMediaTitle(e.target.value)} /><textarea placeholder="Description" value={mediaDescription} onChange={e => setMediaDescription(e.target.value)} /><input type="file" accept="image/*,video/*" onChange={e => setMediaFile(e.target.files?.[0] || null)} required /><button className="button" type="submit">Upload & Publish</button></form></div></main>;
}
