'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

type Leader={id?:string;name:string;role:string;bio:string;photo_url:string;sort_order:number;published:boolean};
type OrgContent={id?:string;section:string;title:string;body:string;metric_value:string;metric_label:string;document_url:string;document_name:string;sort_order:number;published:boolean};
type Gallery={id:string;title:string;description:string|null;media_type:string;media_url:string;published:boolean};
const emptyLeader=():Leader=>({name:'',role:'',bio:'',photo_url:'',sort_order:0,published:true});
const emptyContent=():OrgContent=>({section:'identity',title:'',body:'',metric_value:'',metric_label:'',document_url:'',document_name:'',sort_order:0,published:true});
export default function AdminPage(){
 const [session,setSession]=useState<any>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState('');
 const [leaders,setLeaders]=useState<Leader[]>([]),[contents,setContents]=useState<OrgContent[]>([]),[gallery,setGallery]=useState<Gallery[]>([]);
 const [leader,setLeader]=useState<Leader>(emptyLeader()),[leaderFile,setLeaderFile]=useState<File|null>(null),[editingLeader,setEditingLeader]=useState<string|null>(null);
 const [content,setContent]=useState<OrgContent>(emptyContent()),[docFile,setDocFile]=useState<File|null>(null),[editingContent,setEditingContent]=useState<string|null>(null);
 const [mediaFile,setMediaFile]=useState<File|null>(null),[mediaTitle,setMediaTitle]=useState(''),[mediaDescription,setMediaDescription]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 useEffect(()=>{if(session)load()},[session]);
 async function load(){const [l,c,g]=await Promise.all([supabase.from('organization_leaders').select('*').order('sort_order'),supabase.from('organization_content').select('*').order('sort_order'),supabase.from('gallery_items').select('*').order('created_at',{ascending:false})]);setLeaders(l.data||[]);setContents(c.data||[]);setGallery(g.data||[])}
 async function login(e:React.FormEvent){e.preventDefault();setMessage('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function saveLeader(e:React.FormEvent){e.preventDefault();let photoUrl=leader.photo_url;if(leaderFile){const path=`leaders/${Date.now()}-${leaderFile.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('organization-media').upload(path,leaderFile,{upsert:true});if(up.error)return setMessage(up.error.message);photoUrl=supabase.storage.from('organization-media').getPublicUrl(path).data.publicUrl}if(!leader.name||!leader.role||!photoUrl)return setMessage('Name, role and photo are required.');const payload={...leader,photo_url:photoUrl};const r=editingLeader?await supabase.from('organization_leaders').update(payload).eq('id',editingLeader):await supabase.from('organization_leaders').insert(payload);if(r.error)return setMessage(r.error.message);setMessage(editingLeader?'Leader updated.':'Leader published.');setLeader(emptyLeader());setLeaderFile(null);setEditingLeader(null);load()}
 async function saveContent(e:React.FormEvent){e.preventDefault();if(!content.title)return setMessage('Add a title.');let payload={...content};if(docFile){const path=`documents/${Date.now()}-${docFile.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('organization-documents').upload(path,docFile,{upsert:true});if(up.error)return setMessage(up.error.message);payload.document_url=supabase.storage.from('organization-documents').getPublicUrl(path).data.publicUrl;payload.document_name=docFile.name}const r=editingContent?await supabase.from('organization_content').update(payload).eq('id',editingContent):await supabase.from('organization_content').insert(payload);if(r.error)return setMessage(r.error.message);setMessage(editingContent?'Information updated.':'Information published.');setContent(emptyContent());setDocFile(null);setEditingContent(null);load()}
 async function uploadMedia(e:React.FormEvent){e.preventDefault();if(!mediaFile)return setMessage('Choose an image or video.');const type=mediaFile.type.startsWith('video/')?'video':'image';const path=`${Date.now()}-${mediaFile.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('project-gallery').upload(path,mediaFile,{upsert:true});if(up.error)return setMessage(up.error.message);const url=supabase.storage.from('project-gallery').getPublicUrl(path).data.publicUrl;const r=await supabase.from('gallery_items').insert({title:mediaTitle,description:mediaDescription,media_type:type,media_url:url});if(r.error)return setMessage(r.error.message);setMediaFile(null);setMediaTitle('');setMediaDescription('');setMessage('Gallery item published.');load()}
 async function toggle(table:string,id:string,published:boolean){const r=await supabase.from(table).update({published:!published}).eq('id',id);if(r.error)setMessage(r.error.message);else load()}
 async function remove(table:string,id:string){if(!confirm('Delete this item permanently?'))return;const r=await supabase.from(table).delete().eq('id',id);if(r.error)setMessage(r.error.message);else{setMessage('Deleted.');load()}}
 if(!session)return <main className="admin-page"><div className="admin-card"><span className="eyebrow">ADMINISTRATION</span><h1>Daraja Content Dashboard</h1><p>Sign in to manage donor-facing organizational content.</p><form onSubmit={login} className="admin-form"><input type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="button" type="submit">Sign in</button></form>{message&&<p className="notice">{message}</p>}</div></main>;
 return <main className="admin-page"><div className="admin-head"><div><span className="eyebrow">ADMINISTRATION</span><h1>Daraja Content Dashboard</h1><p>Manage the public website without editing code.</p></div><button className="button secondary-dark" onClick={()=>supabase.auth.signOut()}>Sign out</button></div>{message&&<p className="notice">{message}</p>}
 <div className="admin-section-grid"><form className="admin-card admin-form" onSubmit={saveLeader}><h2>{editingLeader?'Edit Leader':'Leadership'}</h2><p>Add and maintain leader profiles.</p><input placeholder="Full name" value={leader.name} onChange={e=>setLeader({...leader,name:e.target.value})} required/><input placeholder="Position / role" value={leader.role} onChange={e=>setLeader({...leader,role:e.target.value})} required/><textarea placeholder="Biography" value={leader.bio} onChange={e=>setLeader({...leader,bio:e.target.value})}/><input type="number" placeholder="Display order" value={leader.sort_order} onChange={e=>setLeader({...leader,sort_order:Number(e.target.value)})}/><input type="file" accept="image/*" onChange={e=>setLeaderFile(e.target.files?.[0]||null)}/><label><input type="checkbox" checked={leader.published} onChange={e=>setLeader({...leader,published:e.target.checked})}/> Published</label><button className="button" type="submit">{editingLeader?'Update Leader':'Publish Leader'}</button>{editingLeader&&<button className="button button-light" type="button" onClick={()=>{setLeader(emptyLeader());setEditingLeader(null)}}>Cancel</button>}</form>
 <form className="admin-card admin-form" onSubmit={saveContent}><h2>{editingContent?'Edit Information':'Organization & Impact'}</h2><p>Manage identity, impact, governance, safeguarding and transparency.</p><select value={content.section} onChange={e=>setContent({...content,section:e.target.value})}><option value="identity">Mission / Vision / History</option><option value="impact">Impact / Results</option><option value="governance">Governance</option><option value="safeguarding">Safeguarding</option><option value="accountability">Reports / Policies / Transparency</option></select><input placeholder="Title" value={content.title} onChange={e=>setContent({...content,title:e.target.value})} required/><textarea placeholder="Content / explanation" value={content.body} onChange={e=>setContent({...content,body:e.target.value})}/><input placeholder="Impact number (optional)" value={content.metric_value} onChange={e=>setContent({...content,metric_value:e.target.value})}/><input placeholder="Impact label (optional)" value={content.metric_label} onChange={e=>setContent({...content,metric_label:e.target.value})}/><input type="file" accept="application/pdf,.doc,.docx" onChange={e=>setDocFile(e.target.files?.[0]||null)}/><label><input type="checkbox" checked={content.published} onChange={e=>setContent({...content,published:e.target.checked})}/> Published</label><button className="button" type="submit">{editingContent?'Update Information':'Publish Information'}</button>{editingContent&&<button className="button button-light" type="button" onClick={()=>{setContent(emptyContent());setEditingContent(null)}}>Cancel</button>}</form>
 <form className="admin-card admin-form" onSubmit={uploadMedia}><h2>Gallery</h2><p>Publish photographs and videos from programs and activities.</p><input placeholder="Title" value={mediaTitle} onChange={e=>setMediaTitle(e.target.value)}/><textarea placeholder="Description" value={mediaDescription} onChange={e=>setMediaDescription(e.target.value)}/><input type="file" accept="image/*,video/*" onChange={e=>setMediaFile(e.target.files?.[0]||null)} required/><button className="button" type="submit">Upload to Gallery</button></form></div>
 <section className="admin-card admin-list"><h2>Leadership records</h2>{leaders.length===0?<p>No leaders yet.</p>:leaders.map(x=><div className="admin-row" key={x.id}><img src={x.photo_url} alt=""/><div><strong>{x.name}</strong><small>{x.role} · {x.published?'Published':'Hidden'}</small><p>{x.bio}</p></div><div><button onClick={()=>{setEditingLeader(x.id||null);setLeader(x)}}>Edit</button><button onClick={()=>toggle('organization_leaders',x.id||'',x.published)}>{x.published?'Hide':'Publish'}</button><button onClick={()=>remove('organization_leaders',x.id||'')}>Delete</button></div></div>)}</section>
 <section className="admin-card admin-list"><h2>Organization & impact records</h2>{contents.length===0?<p>No records yet.</p>:contents.map(x=><div className="admin-row" key={x.id}><div><small>{x.section} · {x.published?'Published':'Hidden'}</small><strong>{x.title}</strong>{x.metric_value&&<b>{x.metric_value} {x.metric_label}</b>}<p>{x.body}</p>{x.document_url&&<a href={x.document_url} target="_blank" rel="noreferrer">{x.document_name||'Open document'}</a>}</div><div><button onClick={()=>{setEditingContent(x.id||null);setContent(x)}}>Edit</button><button onClick={()=>toggle('organization_content',x.id||'',x.published)}>{x.published?'Hide':'Publish'}</button><button onClick={()=>remove('organization_content',x.id||'')}>Delete</button></div></div>)}</section>
 <section className="admin-card admin-list"><h2>Gallery records</h2>{gallery.length===0?<p>No gallery items yet.</p>:gallery.map(x=><div className="admin-row" key={x.id}><div><small>{x.media_type} · {x.published?'Published':'Hidden'}</small><strong>{x.title||'Untitled media'}</strong><p>{x.description}</p></div><div><button onClick={()=>toggle('gallery_items',x.id,x.published)}>{x.published?'Hide':'Publish'}</button><button onClick={()=>remove('gallery_items',x.id)}>Delete</button></div></div>)}</section>
 </main>;
}
