'use client';
import { useEffect,useState } from 'react';
import { supabase } from '../../lib/supabaseClient';

type Leader={id?:string;name:string;role:string;bio:string;photo_url:string;sort_order:number;published:boolean};
type OrgContent={id?:string;section:string;title:string;body:string;metric_value:string;metric_label:string;document_url:string;document_name:string;sort_order:number;published:boolean};
const emptyLeader=():Leader=>({name:'',role:'',bio:'',photo_url:'',sort_order:0,published:true});
const emptyContent=():OrgContent=>({section:'identity',title:'',body:'',metric_value:'',metric_label:'',document_url:'',document_name:'',sort_order:0,published:true});
export default function AdminPage(){
 const [session,setSession]=useState<any>(null); const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [message,setMessage]=useState('');
 const [leader,setLeader]=useState<Leader>(emptyLeader());const [leaderFile,setLeaderFile]=useState<File|null>(null);const [content,setContent]=useState<OrgContent>(emptyContent());const [docFile,setDocFile]=useState<File|null>(null);const [mediaFile,setMediaFile]=useState<File|null>(null);const [mediaTitle,setMediaTitle]=useState('');const [mediaDescription,setMediaDescription]=useState('');
 useEffect(()=>{supabase.auth.getSession().then(({data})=>setSession(data.session));const {data:l}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s));return()=>l.subscription.unsubscribe()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setMessage('');const {error}=await supabase.auth.signInWithPassword({email,password});if(error)setMessage(error.message)}
 async function uploadLeader(e:React.FormEvent){e.preventDefault();if(!leader.name||!leader.role||!leaderFile)return setMessage('Add the leader name, role and photo.');const path=`leaders/${Date.now()}-${leaderFile.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('organization-media').upload(path,leaderFile);if(up.error)return setMessage(up.error.message);const {data}=supabase.storage.from('organization-media').getPublicUrl(path);const {error}=await supabase.from('organization_leaders').insert({...leader,photo_url:data.publicUrl});if(error)return setMessage(error.message);setLeader(emptyLeader());setLeaderFile(null);setMessage('Leader profile published successfully.')}
 async function publishContent(e:React.FormEvent){e.preventDefault();if(!content.title)return setMessage('Add a title.');let document_url=content.document_url;let document_name=content.document_name;if(docFile){const path=`documents/${Date.now()}-${docFile.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('organization-documents').upload(path,docFile);if(up.error)return setMessage(up.error.message);const {data}=supabase.storage.from('organization-documents').getPublicUrl(path);document_url=data.publicUrl;document_name=docFile.name}const {error}=await supabase.from('organization_content').insert({...content,document_url,document_name});if(error)return setMessage(error.message);setContent(emptyContent());setDocFile(null);setMessage('Organization information published successfully.')}
 async function uploadMedia(e:React.FormEvent){e.preventDefault();if(!mediaFile)return setMessage('Choose an image or video.');const type=mediaFile.type.startsWith('video/')?'video':'image';const path=`${Date.now()}-${mediaFile.name.replace(/[^a-zA-Z0-9._-]/g,'-')}`;const up=await supabase.storage.from('project-gallery').upload(path,mediaFile);if(up.error)return setMessage(up.error.message);const {data}=supabase.storage.from('project-gallery').getPublicUrl(path);const {error}=await supabase.from('gallery_items').insert({title:mediaTitle,description:mediaDescription,media_type:type,media_url:data.publicUrl});if(error)return setMessage(error.message);setMediaFile(null);setMediaTitle('');setMediaDescription('');setMessage('Gallery item published successfully.')}
 if(!session)return <main className="admin-page"><div className="admin-card"><span className="eyebrow">ADMINISTRATION</span><h1>Daraja Content Dashboard</h1><p>Sign in to manage donor-facing organizational content.</p><form onSubmit={login} className="admin-form"><input type="email" placeholder="Admin email" value={email} onChange={e=>setEmail(e.target.value)} required/><input type="password" placeholder="Password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="button" type="submit">Sign in</button></form>{message&&<p className="notice">{message}</p>}</div></main>;
 return <main className="admin-page"><div className="admin-head"><div><span className="eyebrow">ADMINISTRATION</span><h1>Daraja Content Dashboard</h1><p>Manage the public website without editing code.</p></div><button className="button secondary-dark" onClick={()=>supabase.auth.signOut()}>Sign out</button></div>{message&&<p className="notice">{message}</p>}<div className="admin-section-grid">
 <form className="admin-card admin-form" onSubmit={uploadLeader}><h2>Leadership</h2><p>Add leaders with professional profiles.</p><input placeholder="Full name" value={leader.name} onChange={e=>setLeader({...leader,name:e.target.value})} required/><input placeholder="Position / role" value={leader.role} onChange={e=>setLeader({...leader,role:e.target.value})} required/><textarea placeholder="Biography" value={leader.bio} onChange={e=>setLeader({...leader,bio:e.target.value})}/><input type="number" placeholder="Display order" value={leader.sort_order} onChange={e=>setLeader({...leader,sort_order:Number(e.target.value)})}/><input type="file" accept="image/*" onChange={e=>setLeaderFile(e.target.files?.[0]||null)} required/><button className="button" type="submit">Publish Leader</button></form>
 <form className="admin-card admin-form" onSubmit={publishContent}><h2>Organization & Impact</h2><p>Add mission, vision, history, impact metrics, governance or safeguarding information.</p><select value={content.section} onChange={e=>setContent({...content,section:e.target.value})}><option value="identity">Mission / Vision / History</option><option value="impact">Impact / Results</option><option value="governance">Governance</option><option value="safeguarding">Safeguarding</option><option value="accountability">Reports / Policies / Transparency</option></select><input placeholder="Title" value={content.title} onChange={e=>setContent({...content,title:e.target.value})} required/><textarea placeholder="Content / explanation" value={content.body} onChange={e=>setContent({...content,body:e.target.value})}/><input placeholder="Impact number (optional)" value={content.metric_value} onChange={e=>setContent({...content,metric_value:e.target.value})}/><input placeholder="Impact label (optional)" value={content.metric_label} onChange={e=>setContent({...content,metric_label:e.target.value})}/><input type="file" accept="application/pdf,.doc,.docx" onChange={e=>setDocFile(e.target.files?.[0]||null)}/><button className="button" type="submit">Publish Information</button></form>
 <form className="admin-card admin-form" onSubmit={uploadMedia}><h2>Gallery</h2><p>Publish photographs and videos from programs and activities.</p><input placeholder="Title" value={mediaTitle} onChange={e=>setMediaTitle(e.target.value)}/><textarea placeholder="Description" value={mediaDescription} onChange={e=>setMediaDescription(e.target.value)}/><input type="file" accept="image/*,video/*" onChange={e=>setMediaFile(e.target.files?.[0]||null)} required/><button className="button" type="submit">Upload to Gallery</button></form>
 </div></main>;
}