'use client';
import {useEffect,useState} from 'react';
import Link from 'next/link';
import {supabase} from '../../lib/supabaseClient';

type Leader={id:string;name:string;role:string;bio:string|null;photo_url:string};
type Content={id:string;section:string;title:string;body:string|null;metric_value:string|null;metric_label:string|null;document_url:string|null;document_name:string|null;sort_order:number};
export default function AboutPage(){const[leaders,setLeaders]=useState<Leader[]>([]);const[content,setContent]=useState<Content[]>([]);useEffect(()=>{Promise.all([supabase.from('organization_leaders').select('*').eq('published',true).order('sort_order'),supabase.from('organization_content').select('*').eq('published',true).order('sort_order')]).then(([l,c])=>{setLeaders(l.data||[]);setContent(c.data||[])})},[]);const section=(s:string)=>content.filter(x=>x.section===s);const identity=section('identity');const impact=section('impact');const governance=section('governance');const safeguarding=section('safeguarding');const accountability=section('accountability');return <main>
<section className="page-hero"><div className="container"><p className="eyebrow">About Daraja la Utamaduni</p><h1>Know the organization<br/><em>behind the work.</em></h1><p>Our mission, people, programs, impact and accountability—presented clearly for communities, partners and donors.</p></div></section>
<section className="section"><div className="container two-col"><div><p className="eyebrow">Who we are</p><h2>{identity[0]?.title||'A bridge between people, culture and opportunity.'}</h2></div><div className="intro-text">{identity.length?identity.map(x=><div key={x.id}><h3>{x.title}</h3><p>{x.body}</p></div>):<><p>Daraja la Utamaduni Organization is a community-focused organization committed to sustainable development while respecting the knowledge, culture and aspirations of the people we serve.</p><p>Our mission, vision and organizational background can be published from the admin dashboard.</p></>}</div></div></section>
<section className="section section-soft"><div className="container"><div className="section-heading"><div><p className="eyebrow">Leadership</p><h2>The people guiding Daraja.</h2></div><p>Meet the leaders responsible for guiding the organization and its work.</p></div>{leaders.length?<div className="leader-grid">{leaders.map(l=><article className="leader-card" key={l.id}><img src={l.photo_url} alt={l.name}/><div><span>{l.role}</span><h3>{l.name}</h3>{l.bio&&<p>{l.bio}</p>}</div></article>)}</div>:<div className="empty-state"><strong>Leadership profiles will appear here.</strong><p>Leader photos, names, roles and biographies can be uploaded from the admin dashboard.</p></div>}</div></section>
<section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Our impact</p><h2>Evidence of meaningful change.</h2></div><p>Only approved and verified results should be published here.</p></div>{impact.length?<div className="about-impact-grid">{impact.map(x=><article key={x.id} className="about-impact-card">{x.metric_value&&<strong>{x.metric_value}</strong>}<h3>{x.metric_label||x.title}</h3>{x.body&&<p>{x.body}</p>}</article>)}</div>:<div className="empty-state"><strong>Impact information will appear here.</strong><p>Add verified reach, outcomes, results and impact stories from the admin dashboard.</p></div>}</div></section>
<section className="section section-earth"><div className="container two-col"><div><p className="eyebrow eyebrow-light">Governance & safeguarding</p><h2>Responsible work starts with accountability.</h2></div><div className="intro-text">{governance.length?<>{governance.map(x=><div key={x.id}><h3>{x.title}</h3><p>{x.body}</p></div>)}</>:<p>Governance information can be published here so donors and partners can understand how the organization is led and held accountable.</p>}{safeguarding.length&&<>{safeguarding.map(x=><div key={x.id}><h3>{x.title}</h3><p>{x.body}</p></div>)}</>}</div></div></section>
<section className="section section-soft"><div className="container two-col"><div><p className="eyebrow">Transparency & reports</p><h2>Documents partners can review.</h2><p className="intro-text">Annual reports, policies, financial documents and other approved materials can be made available here.</p></div><div className="document-list">{accountability.length?accountability.map(x=><article className="document-card" key={x.id}><span>DOCUMENT</span><h3>{x.title}</h3>{x.body&&<p>{x.body}</p>}{x.document_url&&<a className="button button-outline" href={x.document_url} target="_blank" rel="noreferrer">Open document →</a>}</article>):<div className="empty-state"><strong>Transparency documents will appear here.</strong><p>Upload approved reports and policies from the admin dashboard.</p></div>}</div></div></section>
<section className="section"><div className="container partner-box"><div><p className="eyebrow">Work with us</p><h2>Ready to learn more?</h2><p>We welcome responsible partners who share our commitment to community-led development and sustainable opportunity.</p></div><div className="partner-actions"><Link href="/projects" className="button button-primary">View programs</Link><Link href="/impact" className="button button-outline">Our impact</Link></div></div></section>
</main>}
