import Link from 'next/link';

const sections = [
  ['Mission & vision','Why Daraja la Utamaduni exists, the change we seek and the communities we serve.'],
  ['Governance & leadership','Leadership, board/governance information and clear organizational accountability.'],
  ['Safeguarding','Our commitment to protecting children, young people, communities, staff and partners.'],
  ['Policies & standards','Key organizational policies, ethical standards and responsible-partnership information.'],
  ['Financial transparency','Annual reports, financial information and other documents that help partners understand how resources are managed.'],
  ['Monitoring & learning','How we track activities, outcomes, lessons and improvements across our programs.'],
];
export default function AboutPage(){return <main><section className="hero"><div className="container"><p className="eyebrow">For partners & donors</p><h1>Know the organization<br/><em>behind the work.</em></h1><p className="hero-lead">Daraja la Utamaduni is committed to clear communication, responsible partnerships and accountable community-led development.</p></div></section><section className="section"><div className="container two-col"><div><p className="eyebrow">Due diligence</p><h2>Everything a responsible partner needs to understand us.</h2></div><div className="intro-text"><p>We want prospective donors and partners to be able to understand our purpose, programs, people, governance and approach before deciding to work with us.</p><p>This page is structured as the organization's transparency and due-diligence hub. Verified documents and organization-specific information can be added through the administrative system as they become available.</p></div></div></section><section className="section section-soft"><div className="container"><div className="section-heading"><div><p className="eyebrow">Transparency hub</p><h2>What partners can find</h2></div><p>Important information should be easy to find, understand and review.</p></div><div className="programme-grid">{sections.map(([title,text],i)=><article className="programme-card" key={title}><span className="programme-number">{String(i+1).padStart(2,'0')}</span><h3>{title}</h3><p>{text}</p><span className="card-arrow">↗</span></article>)}</div></div></section><section className="section"><div className="container partner-box"><div><p className="eyebrow">Partnership</p><h2>Let's build trust before we build a program.</h2><p>For institutional, foundation, corporate and community partners, we welcome questions about our work, governance, safeguarding, reporting and partnership requirements.</p></div><div className="partner-actions"><Link href="/#contact" className="button button-primary">Contact Daraja</Link><Link href="/projects" className="button button-outline">View our programs</Link></div></div></section></main>}
